### ISSUE TITLE
colorama.init() breaks sty

### ISSUE THREAD

**Issue by jurgyy** [feluxe/sty#15]
I don't know how this can happen but look:

![image](https://user-images.githubusercontent.com/22032197/51992786-efa4ae00-24ad-11e9-9eed-7f6d0b45c47a.png)

Using Window 10 and the Cmder terminal.

**Comment by feluxe** [comment]
That weird.

I cannot reproduce this on linux.

Could you please show me what `pprint(fg.red)` returns, before and after you import `spacy`? E.g.:

```python
>>> from sty import fg, bg
>>> from pprint import pprint
>>> 
>>> pprint(fg.red)
'\x1b[31m'
>>> 
>>> import spacy
>>> 
>>> pprint(fg.red)
'???'
```




```

**Comment by jurgyy** [comment]
The order of importing seems to have no effect:

![image](https://user-images.githubusercontent.com/22032197/52040070-92a10a80-2536-11e9-863a-b33dc3de4ae2.png)

**Comment by feluxe** [comment]
Thanks for debugging this!

`colorama.init()` is somewhat aggressive in the way that it messes with the terminal session globally. I don't really like this... A library should not alter terminal behaviour globally IMHO... But it looks like they offer a function  `colorama.deinit()` to revoke it.

I don't think there is anything `sty` should do about this. The issue is that `tqdm` alters the terminal session globally by calling `colorama.init()` and doesn't clean up later with `deinit()`. I consider this is a bug in `tqdm`.

So I think you have to go with  `colorama.deinit()` for now... or you could write an issue or pull request at https://github.com/tqdm/tqdm to fix this.

Thanks again for tracing this down!

**Comment by jurgyy** [comment]
`colorama.deinit()` does indeed work!
