### ISSUE TITLE
Show wrong style when importing `tqdm`

### ISSUE THREAD

**Issue by bowen-xu** [feluxe/sty#43]
Testcase:

```
import tqdm
from sty import fg, bg, ef, rs

foo = fg.red + 'This is red text!' + fg.rs
bar = bg.blue + 'This has a blue background!' + bg.rs
baz = ef.italic + 'This is italic text' + rs.italic
qux = fg(201) + 'This is pink text using 8bit colors' + fg.rs
qui = bg(255, 10, 10) + 'This is red text using 24bit colors.' + bg.rs

# Add custom colors:

from sty import Style, RgbFg

fg.orange = Style(RgbFg(255, 150, 50))

buf = fg.orange + 'Yay, Im orange.' + fg.rs

print(foo, bar, baz, qux, qui, buf, sep='\n')
```
after importing tqdm, the `sty` becomes invalid.

It is tested under the environment of python 3.7/3.10, Windows 10, and VS Code 1.6.2. However, I guess other environments are also ok to observe this error.

![image](https://user-images.githubusercontent.com/22338640/150778975-78f637b3-0751-4250-b786-c68d71d01ae0.png)

If `tqdm` is not imported, it display is right.

![image](https://user-images.githubusercontent.com/22338640/150779313-6c5093fd-a386-4b67-b411-d4f803eac504.png)

Could anyone figure out what's wrong with it and how to fix this bug?

**Comment by bowen-xu** [comment]
I find that after `tqdm 3.4.0`, this phenomenon exists, while before `tqdm 3.1.4`, which is also included, the bug disappear. It's weird!

**Comment by feluxe** [comment]
I don't think that this is on sty's side, since sty doesn't override global mechanisms such as `sys.stdout`.

I guess `tqdm` (or some dependency of it) messes with `sys.stdout` in a way that breaks the "ANSI escape codes" which are written to `sys.stdout` (for example when using `print(...)`)

I wouldn't use a library which implicitly messes with `sys.stdout` on import. Such behaviour is intrusive and poor design (IMHO).
